### PR TITLE
Grid visualizations

### PR DESCRIPTION
**Pull request by jsalvatier**
@stuhlmueller 

What you guys saw this morning, but I've added a light grey grid and basic labeling.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
Looks good. Two minor comments:
- It probably make sense to standardize all our code on either spaces or tabs, otherwise diffs will be harder to read. I'd go with two spaces.
- If you're using lodash (or underscore), add it to `package.json` (`npm install --save lodash`) and require it in your file.

**Comment by jsalvatier** [comment]
Yup, sounds good.

**Comment by stuhlmueller** [comment]
Are you planning to add commits to `viz` so that the PR gets updated, or should we merge this now and you'll make the changes later?

**Comment by jsalvatier** [comment]
I was planning to make the changes first.

**Pull request merged**
