### PR TITLE
Webppl upgrade (fixes tests) [not ready for merge]

### PR DESCRIPTION
**Pull request by jsalvatier**
The tests were broken after upgrading webppl. This fixes those changes. Many of the changes are backwards breaking, so not sure if this is ready for prime time yet. This hasn't been thoroughly tested yet either.

### CODE REVIEW

**Comment by stuhlmueller** [comment]
I also did similar work on the [`upgrade-webppl`](https://github.com/agentmodels/webppl-agents/tree/upgrade-webppl) branch (hadn't noticed your work 😞). Two differences I see are that (1) I also got rid of all "erp" terminology and (2) switched to `Infer` syntax everywhere. I'm now working on upgrading agentmodels based on these changes [here](https://github.com/agentmodels/agentmodels.org/tree/upgrade-webppl).

**Comment by jsalvatier** [comment]
Darn, I should have made it clearer that I had done this work. 

Interesting, I hadn't seen the Infer syntax yet. It seems unnecessarily verbose for our purposes. I assume the reason you might use it is to be able to change it programmatically, but that seems like something that's rarely going to happen.

**Comment by owainevans** [comment]
what's the status of this pull request?

**Comment by stuhlmueller** [comment]
This is subsumed by my PR (which you already merged).

**Pull request closed without merging**
